config/routes.rb
Gemkitty::Application.routes.draw do
  resources :legal_contracts

  resources :contacts

  resources :sponsors

  resources :employees

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :sponsors
  has_many :contacts, through: :sponsors
  has_many :legal_contracts, through: :sponsors
  attr_accessible :department, :email, :first_name, :last_name, :phone_num, :position
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :department %><br />
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :phone_num %><br />
    <%= f.text_field :phone_num %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <tr>
    <th>Last name</th>
    <th>First name</th>
    <th>Position</th>
    <th>Department</th>
    <th>Phone num</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.last_name %></td>
    <td><%= employee.first_name %></td>
    <td><%= employee.position %></td>
    <td><%= employee.department %></td>
    <td><%= employee.phone_num %></td>
    <td><%= employee.email %></td>
    <td><%= link_to 'Show', employee %></td>
    <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
    <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Last name:</b>
  <%= @employee.last_name %>
</p>

<p>
  <b>First name:</b>
  <%= @employee.first_name %>
</p>

<p>
  <b>Position:</b>
  <%= @employee.position %>
</p>

<p>
  <b>Department:</b>
  <%= @employee.department %>
</p>

<p>
  <b>Phone num:</b>
  <%= @employee.phone_num %>
</p>

<p>
  <b>Email:</b>
  <%= @employee.email %>
</p>


<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>