config/routes.rb
Gemkitty::Application.routes.draw do
  resources :legal_contracts

  resources :contacts

  resources :sponsors

  resources :employees

end

app/models/legal_contract.rb
class LegalContract < ActiveRecord::Base
  belongs_to :sponsor
  attr_accessible :contract_description, :contract_status, :sponsor_id, :sponsor
end

app/controllers/legal_contracts_controller.rb
class LegalContractsController < ApplicationController
  # GET /legal_contracts
  # GET /legal_contracts.json
  def index
    @legal_contracts = LegalContract.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @legal_contracts }
    end
  end

  # GET /legal_contracts/1
  # GET /legal_contracts/1.json
  def show
    @legal_contract = LegalContract.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @legal_contract }
    end
  end

  # GET /legal_contracts/new
  # GET /legal_contracts/new.json
  def new
    @legal_contract = LegalContract.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @legal_contract }
    end
  end

  # GET /legal_contracts/1/edit
  def edit
    @legal_contract = LegalContract.find(params[:id])
  end

  # POST /legal_contracts
  # POST /legal_contracts.json
  def create
    @legal_contract = LegalContract.new(params[:legal_contract])

    respond_to do |format|
      if @legal_contract.save
        format.html { redirect_to @legal_contract, notice: 'Legal contract was successfully created.' }
        format.json { render json: @legal_contract, status: :created, location: @legal_contract }
      else
        format.html { render action: "new" }
        format.json { render json: @legal_contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /legal_contracts/1
  # PUT /legal_contracts/1.json
  def update
    @legal_contract = LegalContract.find(params[:id])

    respond_to do |format|
      if @legal_contract.update_attributes(params[:legal_contract])
        format.html { redirect_to @legal_contract, notice: 'Legal contract was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @legal_contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /legal_contracts/1
  # DELETE /legal_contracts/1.json
  def destroy
    @legal_contract = LegalContract.find(params[:id])
    @legal_contract.destroy

    respond_to do |format|
      format.html { redirect_to legal_contracts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/legal_contracts_helper.rb
module LegalContractsHelper
end

app/views/legal_contracts/_form.html.erb
<%= form_for(@legal_contract) do |f| %>
  <% if @legal_contract.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@legal_contract.errors.count, "error") %> prohibited this legal_contract from being saved:</h2>

      <ul>
      <% @legal_contract.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :contract_status %><br />
    <%= f.text_field :contract_status %>
  </div>
  <div class="field">
    <%= f.label :contract_description %><br />
    <%= f.text_area :contract_description %>
  </div>
  <div class="field">
    <%= f.label :sponsor_id %><br />
    <%= f.collection_select(:sponsor_id,Sponsor.all,:id,:sponsor_name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/legal_contracts/edit.html.erb
<h1>Editing legal_contract</h1>

<%= render 'form' %>

<%= link_to 'Show', @legal_contract %> |
<%= link_to 'Back', legal_contracts_path %>

app/views/legal_contracts/index.html.erb
<h1>Listing legal_contracts</h1>

<table>
  <tr>
    <th>Contract status</th>
    <th>Contract description</th>
    <th>Sponsor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @legal_contracts.each do |legal_contract| %>
  <tr>
    <td><%= legal_contract.contract_status %></td>
    <td><%= legal_contract.contract_description %></td>
    <td><%= legal_contract.sponsor.sponsor_name %></td>
    <td><%= link_to 'Show', legal_contract %></td>
    <td><%= link_to 'Edit', edit_legal_contract_path(legal_contract) %></td>
    <td><%= link_to 'Destroy', legal_contract, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Legal contract', new_legal_contract_path %>

app/views/legal_contracts/new.html.erb
<h1>New legal_contract</h1>

<%= render 'form' %>

<%= link_to 'Back', legal_contracts_path %>

app/views/legal_contracts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Contract status:</b>
  <%= @legal_contract.contract_status %>
</p>

<p>
  <b>Contract description:</b>
  <%= @legal_contract.contract_description %>
</p>

<p>
  <b>Sponsor:</b>
  <%= @legal_contract.sponsor.sponsor_name %>
</p>


<%= link_to 'Edit', edit_legal_contract_path(@legal_contract) %> |
<%= link_to 'Back', legal_contracts_path %>