config/routes.rb
Gemkitty::Application.routes.draw do
  resources :legal_contracts

  resources :contacts

  resources :sponsors

  resources :employees

end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  belongs_to :employee
  has_many :contacts
  has_many :legal_contracts
  attr_accessible :employee_id, :sponsor_amount, :sponsor_name, :sponsor_type, :employee
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  # GET /sponsors
  # GET /sponsors.json
  def index
    @sponsors = Sponsor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sponsors }
    end
  end

  # GET /sponsors/1
  # GET /sponsors/1.json
  def show
    @sponsor = Sponsor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sponsor }
    end
  end

  # GET /sponsors/new
  # GET /sponsors/new.json
  def new
    @sponsor = Sponsor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sponsor }
    end
  end

  # GET /sponsors/1/edit
  def edit
    @sponsor = Sponsor.find(params[:id])
  end

  # POST /sponsors
  # POST /sponsors.json
  def create
    @sponsor = Sponsor.new(params[:sponsor])

    respond_to do |format|
      if @sponsor.save
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully created.' }
        format.json { render json: @sponsor, status: :created, location: @sponsor }
      else
        format.html { render action: "new" }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sponsors/1
  # PUT /sponsors/1.json
  def update
    @sponsor = Sponsor.find(params[:id])

    respond_to do |format|
      if @sponsor.update_attributes(params[:sponsor])
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sponsors/1
  # DELETE /sponsors/1.json
  def destroy
    @sponsor = Sponsor.find(params[:id])
    @sponsor.destroy

    respond_to do |format|
      format.html { redirect_to sponsors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/sponsors/_form.html.erb
<%= form_for(@sponsor) do |f| %>
  <% if @sponsor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sponsor.errors.count, "error") %> prohibited this sponsor from being saved:</h2>

      <ul>
      <% @sponsor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sponsor_name %><br />
    <%= f.text_field :sponsor_name %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br />
    <%= f.collection_select(:employee_id,Employee.all,:id,:last_name) %>
  </div>
  <div class="field">
    <%= f.label :sponsor_type %><br />
    <%= f.text_field :sponsor_type %>
  </div>
  <div class="field">
    <%= f.label :sponsor_amount %><br />
    <%= f.text_field :sponsor_amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sponsors/edit.html.erb
<h1>Editing sponsor</h1>

<%= render 'form' %>

<%= link_to 'Show', @sponsor %> |
<%= link_to 'Back', sponsors_path %>

app/views/sponsors/index.html.erb
<h1>Listing sponsors</h1>

<table>
  <tr>
    <th>Sponsor name</th>
    <th>Employee</th>
    <th>Sponsor type</th>
    <th>Sponsor amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sponsors.each do |sponsor| %>
  <tr>
    <td><%= sponsor.sponsor_name %></td>
    <td><%= sponsor.employee.last_name %></td>
    <td><%= sponsor.sponsor_type %></td>
    <td><%= sponsor.sponsor_amount %></td>
    <td><%= link_to 'Show', sponsor %></td>
    <td><%= link_to 'Edit', edit_sponsor_path(sponsor) %></td>
    <td><%= link_to 'Destroy', sponsor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sponsor', new_sponsor_path %>

app/views/sponsors/new.html.erb
<h1>New sponsor</h1>

<%= render 'form' %>

<%= link_to 'Back', sponsors_path %>

app/views/sponsors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sponsor name:</b>
  <%= @sponsor.sponsor_name %>
</p>

<p>
  <b>Employee:</b>
  <%= @sponsor.employee.last_name %>
</p>

<p>
  <b>Sponsor type:</b>
  <%= @sponsor.sponsor_type %>
</p>

<p>
  <b>Sponsor amount:</b>
  <%= @sponsor.sponsor_amount %>
</p>


<%= link_to 'Edit', edit_sponsor_path(@sponsor) %> |
<%= link_to 'Back', sponsors_path %>