config/routes.rb
Gemkitty::Application.routes.draw do
  resources :legal_contracts

  resources :contacts

  resources :sponsors

  resources :employees

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :sponsor
  attr_accessible :email, :first_name, :last_name, :location, :phone_num, :sponsor_id, :sponsor
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :sponsor_id %><br />
    <%= f.collection_select(:sponsor_id,Sponsor.all,:id,:sponsor_name) %>
  </div>
  <div class="field">
    <%= f.label :phone_num %><br />
    <%= f.number_field :phone_num %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <tr>
    <th>Last name</th>
    <th>First name</th>
    <th>Sponsor</th>
    <th>Phone num</th>
    <th>Email</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contacts.each do |contact| %>
  <tr>
    <td><%= contact.last_name %></td>
    <td><%= contact.first_name %></td>
    <td><%= contact.sponsor.sponsor_name %></td>
    <td><%= contact.phone_num %></td>
    <td><%= contact.email %></td>
    <td><%= contact.location %></td>
    <td><%= link_to 'Show', contact %></td>
    <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
    <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Last name:</b>
  <%= @contact.last_name %>
</p>

<p>
  <b>First name:</b>
  <%= @contact.first_name %>
</p>

<p>
  <b>Sponsor:</b>
  <%= @contact.sponsor.sponsor_name %>
</p>

<p>
  <b>Phone num:</b>
  <%= @contact.phone_num %>
</p>

<p>
  <b>Email:</b>
  <%= @contact.email %>
</p>

<p>
  <b>Location:</b>
  <%= @contact.location %>
</p>


<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>